# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2
from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x12\x41\x63tionsLink.Common\x1a\x0b\x65rror.proto\x1a google/protobuf/descriptor.proto\"\t\n\x07\x43ommand\"2\n\x06Result\x12(\n\x06status\x18\x01 \x01(\x0b\x32\x18.ActionsLink.Error.Error:/\n\x06minVal\x12\x1d.google.protobuf.FieldOptions\x18\xd1\x86\x03 \x01(\x05:/\n\x06maxVal\x12\x1d.google.protobuf.FieldOptions\x18\xd2\x86\x03 \x01(\x05:0\n\x07stepVal\x12\x1d.google.protobuf.FieldOptions\x18\xd3\x86\x03 \x01(\x05\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COMMAND']._serialized_start=83
  _globals['_COMMAND']._serialized_end=92
  _globals['_RESULT']._serialized_start=94
  _globals['_RESULT']._serialized_end=144
# @@protoc_insertion_point(module_scope)
