# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: error.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'error.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x65rror.proto\x12\x11\x41\x63tionsLink.Error\"<\n\x05\x45rror\x12%\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x17.ActionsLink.Error.Code\x12\x0c\n\x04text\x18\x02 \x01(\t*s\n\x04\x43ode\x12\x0b\n\x07Success\x10\x00\x12\x13\n\x0fOperationFailed\x10\x01\x12\x15\n\x11OperationCanceled\x10\x02\x12\x19\n\x15OperationNotSupported\x10\x03\x12\x17\n\x13ResourceUnavailable\x10\x04\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'error_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODE']._serialized_start=96
  _globals['_CODE']._serialized_end=211
  _globals['_ERROR']._serialized_start=34
  _globals['_ERROR']._serialized_end=94
# @@protoc_insertion_point(module_scope)
