# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kvstorage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'kvstorage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import error_pb2 as error__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fkvstorage.proto\x12\x15\x41\x63tionsLink.KVStorage\x1a\x0b\x65rror.proto\"%\n\x07\x45lement\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r\"3\n\x05Write\x12*\n\x02\x65l\x18\x01 \x01(\x0b\x32\x1e.ActionsLink.KVStorage.Element\"\x13\n\x04Read\x12\x0b\n\x03key\x18\x01 \x01(\r\"q\n\x0cReadResponse\x12,\n\x02\x65l\x18\x01 \x01(\x0b\x32\x1e.ActionsLink.KVStorage.ElementH\x00\x12)\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x18.ActionsLink.Error.ErrorH\x00\x42\x08\n\x06Resultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kvstorage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELEMENT']._serialized_start=55
  _globals['_ELEMENT']._serialized_end=92
  _globals['_WRITE']._serialized_start=94
  _globals['_WRITE']._serialized_end=145
  _globals['_READ']._serialized_start=147
  _globals['_READ']._serialized_end=166
  _globals['_READRESPONSE']._serialized_start=168
  _globals['_READRESPONSE']._serialized_end=281
# @@protoc_insertion_point(module_scope)
