# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: system.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'system.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0csystem.proto\x12\x12\x41\x63tionsLink.System\x1a\x0c\x63ommon.proto\"M\n\x0f\x46irmwareVersion\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\x12\r\n\x05patch\x18\x03 \x01(\r\x12\r\n\x05\x62uild\x18\x04 \x01(\t\"\x91\x01\n\nPowerState\x12<\n\x04mode\x18\x01 \x01(\x0e\x32..ActionsLink.System.PowerState.SystemPowerMode\"E\n\x0fSystemPowerMode\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01\x12\x0b\n\x07STANDBY\x10\x02\x12\x14\n\x10SHUTDOWN_REQUEST\x10\x03\"}\n\x08OffTimer\x12\x31\n\x05state\x18\x01 \x01(\x0e\x32\".ActionsLink.System.OffTimer.State\x12\x1a\n\x07minutes\x18\x02 \x01(\rB\t\x88\xb5\x18\x05\x90\xb5\x18\xf0\x01\"\"\n\x05State\x12\x0c\n\x08\x44ISABLED\x10\x00\x12\x0b\n\x07\x45NABLED\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'system_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_OFFTIMER'].fields_by_name['minutes']._loaded_options = None
  _globals['_OFFTIMER'].fields_by_name['minutes']._serialized_options = b'\210\265\030\005\220\265\030\360\001'
  _globals['_FIRMWAREVERSION']._serialized_start=50
  _globals['_FIRMWAREVERSION']._serialized_end=127
  _globals['_POWERSTATE']._serialized_start=130
  _globals['_POWERSTATE']._serialized_end=275
  _globals['_POWERSTATE_SYSTEMPOWERMODE']._serialized_start=206
  _globals['_POWERSTATE_SYSTEMPOWERMODE']._serialized_end=275
  _globals['_OFFTIMER']._serialized_start=277
  _globals['_OFFTIMER']._serialized_end=402
  _globals['_OFFTIMER_STATE']._serialized_start=368
  _globals['_OFFTIMER_STATE']._serialized_end=402
# @@protoc_insertion_point(module_scope)
